# Login page locator
signIn_locator = "xpath://a[contains(text(),'Signup / Login')]"
SignIn_email_box = "xpath://body/div[2]/div[1]/div[2]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/input[1]"
SignIn_Password_box = "xpath://body/div[2]/div[1]/div[2]/div[1]/div[2]/form[1]/div[1]/div[1]/div[2]/input[1]"
SignIn_submit_Btn = "xpath://button[contains(text(),'LOGIN')]"
# Sign Up
Registration_link = "xpath://a[contains(text(),'Register')]"
signup_phone_number = "xpath://body/div[2]/div[1]/div[2]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/input[1]"
drag_start = "xpath://span[@id='nc_2_n1z']"
drag_stop = "id:nc_2__voice"
signup_password = "xpath://body/div[2]/div[1]/div[2]/div[1]/div[2]/form[1]/div[1]/div[1]/div[3]/input[1]"
month_box = "xpath://span[contains(text(),'Month')]"
month_select = "xpath://li[contains(text(),'May')]"
day_box = "xpath://span[contains(text(),'Day')]"
day_select = "xpath://li[contains(text(),'06')]"
year_box = "xpath://span[contains(text(),'Year')]"
year_select = "xpath://li[contains(text(),'1996')]"
gender_box = "xpath://body/div[2]/div[1]/div[2]/div[1]/div[2]/form[1]/div[1]/div[1]/div[4]/div[2]/div[1]/span[1]/span[1]"
gender_select = "xpath://body/div[5]/div[1]/div[1]/ul[1]/li[1]"
full_name = "xpath://body/div[2]/div[1]/div[2]/div[1]/div[2]/form[1]/div[1]/div[2]/div[1]/input[1]"
check_box = "id:enableNewsletter"
signup_submit_btn = "xpath://button[contains(text(),'SIGN UP')]"

# Language Change
language_select = "xpath://span[contains(text(),'ভাষা')]"
bangla_language = 'xpath://*[@id="lzdSwitchPop"]/div/div[1]/span'
# search
search_bar = "id:q"
search_btn = "xpath://button[contains(text(),'SEARCH')]"
best_match ="xpath://div[contains(text(),'Best Match')]"
low_to_high ="xpath://div[contains(text(),'Price low to high')]"
high_to_low = "xpath://div[contains(text(),'Price high to low')]"
list_view = "xpath://body/div[@id='root']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/span[2]/i[1]"
traditional_laptop = "xpath://a[contains(text(),'Traditional Laptops')]"
gaming_laptop = "xpath://a[contains(text(),'Gaming Laptops')]"
basic_laptop ="xpath://a[contains(text(),'Basic')]"
asus_laptop = "xpath://span[contains(text(),'ASUS')]"
walton_laptop = "xpath://span[contains(text(),'Walton Computers')]"
Avita_Laptop = "xpath://span[contains(text(),'Avita')]"
Service = "xpath://div[contains(text(),'Service')]"
installment = "xpath://span[contains(text(),'Installment')]"
cash_on_delivery ="xpath://span[contains(text(),'Cash On Delivery')]"
Bangladesh = "xpath://body[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/div[2]/div[1]/div[1]/label[1]/span[2]"
china = "xpath://body[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/div[2]/div[1]/div[1]/label[2]/span[2]"